[package]
name = "wav_derivative"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fft = "0.4.0"
plotters = "0.3.4"
rustfft = "6.1.0"
wav = "1.0.0"
